mage: jangrewe/gitlab-ci-android                                  
                                                                   
before_script:                                                     
  - export GRADLE_USER_HOME=$(pwd)/.gradle                         
  - chmod +x /builds/piske-alex/pfa-react/cordova/platforms/android/gradlew                   
                                                                   
cache:                                                             
  key: ${CI_PROJECT_ID}                                            
  paths:                                                           
    - .gradle/                                                     
                                                                   
stages:                                                            
  - build                                                          
  - release                                                        
                                                                   
lintDebug:                                                         
  stage: build                                                     
  script:                                                          
    - /builds/piske-alex/pfa-react/cordova/platforms/android/gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint                                         
                                                                   
assembleDebug:                                                     
  stage: build                                                     
  script:                                                          
    - /builds/piske-alex/pfa-react/cordova/platforms/android/gradlew assembleDebug            
                                                                   
assembleRelease:                                                   
  stage: release                                                   
  script:                                                          
    - echo $KEYSTORE_FILE | base64 -d > my.keystore                
    - /builds/piske-alex/pfa-react/cordova/platforms/android/gradlew assembleRelease          
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore     
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD 
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS              
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD        
  artifacts:                                                       
    paths:                                                         
      - /builds/piske-alex/pfa-react/cordova/platforms/android/app/build/outputs/apk/release                              
      - CHANGELOG                            
