image: jangrewe/gitlab-ci-android                                  

stages:                                                            
  - build                                                          
  - release                                                        
                                                                   
lintDebug:                                                         
  stage: build                                                     
  script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./cordova/platforms/android/gradlew
    - ./cordova/platforms/android/gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
                                                                   
assembleDebug:                                                     
  stage: build                                                     
  script:
    - chmod +x /builds/piske-alex/pfa-react/cordova/platforms/android/gradlew
    - ./cordova/platforms/android/gradlew assembleDebug
                                                                   
assembleRelease:                                                   
  stage: release                                                   
  script:
    - chmod +x ./cordova/platforms/android/gradlew
    - echo $KEYSTORE_FILE | base64 -d > my.keystore                
    - ./cordova/platforms/android/gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore     
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD 
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS              
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD        
  artifacts:                                                       
    paths:                                                         
      - ./cordova/platforms/android/app/release
      - CHANGELOG                            
